{%- if cookiecutter.sphinx == "y" %}

name: "Sync website"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: "Build docs"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install --only docs

      - name: Build docs
        run: make docs-html

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/html/

  deploy:
    name: "Publish Docs"
    needs: build
    
    # See the full reference for available parameters https://docs.int.bayer.com/ref/
    uses: bayer-int/actions-workflows/.github/workflows/publish-docs.yml@main
    with:
      namespace: '{{cookiecutter.project_slug}}'
      artifact: docs
      dir:      docs
      preview:  ${{ github.ref != 'refs/heads/main' && github.run_id || '' }}

{%- endif%}